eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.181:8761/eureka/
      
spring:
  redis:
    host: 192.168.1.159
    port: 6373
    password: Passw0rd

user:
  token:
    url: /getToken