spring:
  redis:
    host: 192.168.1.159
    port: 6373
    password: Passw0rd
  datasource:
    url: jdbc:mysql://192.168.1.169:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: userrw
    password: readwrite
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 2
    initialSize: 1
