spring:
  datasource:
    url: jdbc:mysql://192.168.1.169:3306/system_user?useUnicode=true&characterEncoding=utf-8
    data-username: userrw
    data-password: readwrite
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.cwgj.system.user.pojo
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.cwgj.system.user.base.BaseDao
  not-empty: false
  identity: MYSQL
logging:
  file: logback.xml