### 数据库配置
spring.datasource.url=jdbc:mysql://192.168.1.169:3306/system_user?useUnicode=true&characterEncoding=utf-8
spring.datasource.username=userrw
spring.datasource.password=readwrite
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.driverClassName=com.mysql.jdbc.Driver

### mybatis通用Mapper
mybatis.type-aliases-package=com.cwgj.system.user.pojo
mybatis.mapper-locations=classpath:mapper/*.xml
# 多个接口逗号隔开
mapper.mappers=com.cwgj.system.user.base.BaseDao
mapper.identity=MYSQL
mapper.not-empty=false

### 分页插件
pagehelper.helperDialect=mysql
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql