eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.181:8761/eureka/

spring:
  redis:
    host: 192.168.1.158
    port: 6379
  datasource:
    url: jdbc:mysql://192.168.1.169:3306/system_user?useUnicode=true&characterEncoding=utf-8
    username: userrw
    password: readwrite
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 2
    initialSize: 1
